version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - "80:80" # local 80
    volumes:
      - '.:/var/www/html'
      - './docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
    networks:
      - web

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: ${APP_NAME}-adminer
    depends_on:
      - php
      - mysql
    ports:
      - '81:8080'
    networks:
      - web

  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    tty: true # shel access
    ports:
      - "3306:3306" # local 8081
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/docker-entrypoint-initdb.d
    networks:
      - web

  php:
    build:
      context: ./docker-compose/dockerfiles # Directory to search for
      dockerfile: php.dockerfile
    container_name: ${APP_NAME}-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - web

networks:
  web:

volumes:
  mysql-data:
    external: true
